# =========================== Basic Settings ===========================
name: fmgproducts_finetune
model_restore: model_onur/
dataset: fmgproducts
random_crop: False
val: False
log_dir: logs/fmgproducts_v1

# =========================== Training ===========================
max_iters: 10000
batch_size: 4
viz_max_out: 10
val_psteps: 1000

# =========================== Data ===========================
data_flist: data/fmgproducts/train_shuffled.flist
mask_flist: data/fmgproducts/mask/
img_shapes: [1000, 1000, 3]

# Mask parameters required by random_bbox()
height: 256
width: 256
max_delta_height: 32
max_delta_width: 32
vertical_margin: 32
horizontal_margin: 32

# =========================== Loss ===========================
ae_loss: True
l1_loss: True
l1_loss_alpha: 1.0

# =========================== Model ===========================
gan: sngan
gan_loss_alpha: 1
gan_with_mask: True
discounted_mask: True
guided: False
edge_threshold: 0.6
padding: SAME
